# Generated by Django 5.0.4 on 2024-04-23 03:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('open_library_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('author', models.TextField()),
                ('publish_date', models.DateField()),
                ('cover_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
            options={
                'unique_together': {('user_id', 'book')},
            },
        ),
    ]
