# Generated by Django 5.0.4 on 2024-04-24 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_name_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
