# Generated by Django 5.0.4 on 2024-04-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie_delete_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.CharField(max_length=100),
        ),
    ]
