# Generated by Django 5.0.4 on 2024-04-22 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usermovies'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermovies',
            unique_together={('user_id', 'movie')},
        ),
    ]
