# Generated by Django 5.0.4 on 2024-04-24 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usermovies_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovies',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(blank=True, default='No name provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(blank=True, default='No description provided'),
        ),
    ]
