# Generated by Django 5.0.4 on 2024-04-25 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usermovies_date_alter_movie_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
