# Generated by Django 5.0.4 on 2024-04-22 21:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tmdb_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('release_date', models.DateField()),
                ('poster_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSerie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.serie')),
            ],
            options={
                'unique_together': {('user_id', 'serie')},
            },
        ),
    ]
