# Generated by Django 5.0.4 on 2024-04-22 22:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mal_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('synopsis', models.TextField()),
                ('release_date', models.DateField()),
                ('end_date', models.DateField()),
                ('poster_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAnime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.anime')),
            ],
            options={
                'unique_together': {('user_id', 'anime')},
            },
        ),
    ]
