# Generated by Django 5.0.4 on 2024-04-23 03:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('igdb_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('release_date', models.DateField()),
                ('poster_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
            options={
                'unique_together': {('user_id', 'game')},
            },
        ),
    ]
